### PR TITLE
Add Kite Compositor

### PR DESCRIPTION
**Pull request by jrhodes**
I've been following this site for a bit, and it's grown into a fantastic list of curated tools!

I hope you'll consider including [Kite Compositor](https://kiteapp.co), an animation design app for the Mac. You can think of it most similar to Origami Studio or Sketch.

### CODE REVIEW

**Comment by jrhodes** [comment]
@abstractalgo Yes, no problem! I'll resize the image. I was following the (maybe outdated?) README asking for a larger image:
> please provide a high-resolution image of at least 1200px wide with your pull request

**Comment by jrhodes** [comment]
Updated to reduce image dimensions and size to 600 x 340 px!

**Comment by arun-is** [comment]
Hi @jrhodes you are indeed right about the README. Sorry that I missed your initial message, I've been manually resizing images and checking them back in. I'll look at this PR and merge ASAP

**Comment by jrhodes** [comment]
No worries, @arun-is! Thank you for curating such a great collection of tools and ideas.

**Pull request merged**
