### PR TITLE
Add Modyfi

### PR DESCRIPTION
**Pull request by pierscowburn**
Great list! 🙌 

We'd love to add [modyfi.io](https://www.modyfi.io/), the next generation, browser-based, collaborative image creation platform that we're building.

### CODE REVIEW

**Review by arun-is — CHANGES_REQUESTED** [review]
@pierscowburn would you be able to attach a higher resolution image? I'm keeping high res images for the future when Astro automatically builds images into multiple sizes/formats. More info in this issue: #23

**Comment by pierscowburn** [comment]
Sure! What dimensions and format would you like? The original screenshot is 1923 x 1107, png.

**Comment by arun-is** [comment]
> Sure! What dimensions and format would you like? The original screenshot is 1923 x 1107, png.

The size will work perfectly!

**Comment by arun-is** [comment]
Feel free to attach the image to this PR as a comment.

**Comment by pierscowburn** [comment]
Here you go! Attaching as a comment as requested in case you're trying to avoid bloating the repo history with an uncompressed file; also happy to update the PR to include the high res image if you'd rather go that route.

modyfi

**Comment by pierscowburn** [comment]
Hey @arun-is – just checking if you need anything else from us to get this live?

**Comment by arun-is** [comment]
@pierscowburn nope! thanks for the file. I'll run some checks and merge it.

**Pull request merged**
